# Generated by Django 2.2 on 2023-08-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='accessable_prodts',
        ),
        migrations.RemoveField(
            model_name='products',
            name='desc2',
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
